[package]
name = "warundred-rust"
version = "0.1.0"
authors = ["Sasha Syrotenko <alex.syrotenko.official@gmail.com>"]
edition = "2021"
rust-version = "1.73"

[dependencies]
axum = "0.6.20"
diesel = { version = "2.1.3", features = ["postgres"] }
serde = "1.0.188"
tracing-subscriber = "0.3.17"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.37"