[workspace]
members = [
    "warhundred-app",
    "warhundred-be",
]

resolver = "2"

[workspace.dependencies]
async-trait = "0.1"
axum = "0.7.3"
axum-login = "0.16"
axum-macros = "0.4"
deadpool-diesel = { version = "0.6", features = ["sqlite"] }
diesel = { version = "2.2", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
dotenvy = "0.15.7"
eyre = "0.6.12"
password-auth = "1.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0.12"
