services:
  caddy:
    image: caddy:2.7
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - caddy_logs:/var/log/caddy
    configs:
      - source: caddy_config_file
        target: /etc/caddy/Caddyfile
    command: caddy run --config /etc/caddy/Caddyfile
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure

  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data

  server:
    image: ghcr.io/fly-style/warhundred-rs:${GIT_COMMIT_HASH:-latest}
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///app/database.db
      - REDIS_URL=redis://dragonfly:6379
    volumes:
      - sqlitedata:/app
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - caddy
      - dragonfly

volumes:
  dragonflydata:
  caddy_data:
  caddy_config:
  caddy_logs:
  sqlitedata:

configs:
  caddy_config_file:
    file: ./Caddyfile
