// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerSession {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub nickname: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub token: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub level: u32,
    #[prost(uint32, tag = "5")]
    pub session_started_at: u32,
    #[prost(bool, tag = "6")]
    pub is_in_battle: bool,
    #[prost(string, optional, tag = "7")]
    pub link_to_battle: ::core::option::Option<::prost::alloc::string::String>,
}
